name: Hello World

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print a message
        run: echo "Hello from GitHub Actions!"

      - name: Show the runner OS
        run: uname -a

      - name: Show current directory
        run: pwd && ls -la

      - name: Injects this enviroment variable automatically
        run: echo "Runner: $RUNNER_OS"

